name: deploy nexturl to vercel
on: [push, pull_request]
jobs:
  vercel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  deploy:
    name: deploy site to vercel
    runs-on: ubuntu-latest
    steps:
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
